### ISSUE TITLE
The issue of infinite loop here

### ISSUE THREAD

**Issue by whoosher** [czq142857/IM-NET-pytorch#24]
Dear ZhiqinChen:
Thank you for sharing your code and I'm sorry to bother you

I'm a student Master student in South Korea.
I have an issue testing the IM_AE
the error which is 'infinite loop here!' occurred in my cmd window.
I can not find the reason for this issue
Could you please interpret or clarify this issue to find the reason why?

**Comment by czq142857** [comment]
It means the output shape is empty. The default testing setting is to output a mesh and sampled points. The 'infinite loop' error is because no point can be sampled on the mesh.

There are some issues in your testing because the output should not be empty. But if you are okay with empty outputs, you can just replace all "test_mesh_point" with "test_mesh" in *main.py*.

**Comment by whoosher** [comment]
Thanks for the helpful answer to my question.
the problem is the point sampling part.
my dataset has a different shape in dimension (e.g. the first dimension is an odd number 255 like that)
It can learn and have excellent performance for 3D object
I really appreciate your outstanding work.
Thanks for the author and best regard!
